import os
import numpy as np
import matplotlib.pyplot as plt
from qiskit import QuantumCircuit, transpile
from qiskit.circuit import ParameterVector
from qiskit_aer import AerSimulator
from qiskit.quantum_info import Statevector, partial_trace, Pauli
from qiskit.visualization.bloch import Bloch
from scipy.spatial.distance import pdist
from scipy.stats import pearsonr
import qiskit_algorithms

# SPSA is used manually for gradient estimation (not as a black-box optimizer)
from qiskit_algorithms.utils import algorithm_globals


# Set random seed directly
qiskit_algorithms.utils.algorithm_globals.random_seed = 42
np.random.seed(42)


def load_word2vec_embeddings(filepath):
    """
    Loads Word2Vec embeddings previously saved by word2Vec.py.

    Expected file format (plain text, generated by _save_embeddings):
        Line 0  : \"# word  d0  d1  ...  dN  [# comment]\"   (header, ignored)
        Lines 1+: \"<word>  v0  v1  ...  vN\"

    Parameters
    ----------
    filepath : str
        Path to the .txt file (e.g. \"word2vec_embeddings.txt\" or
        \"word2vec_embeddings_2d.txt\").

    Returns
    -------
    embeddings : dict[str, np.ndarray]
        Mapping {word: vector}. Preserves the insertion order from the file.

    Raises
    ------
    FileNotFoundError
        If *filepath* does not exist. Run word2Vec.py first to generate it.
    """
    if not os.path.isfile(filepath):
        raise FileNotFoundError(
            f"Word2Vec embedding file not found: '{filepath}'\n"
            "Please run word2Vec.py first to generate the embeddings."
        )

    embeddings = {}
    with open(filepath, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue  # skip header / blank lines
            # Strip any inline comment (everything after a bare '#' token)
            if "  #" in line:
                line = line[: line.index("  #")]
            parts = line.split()
            word = parts[0]
            vec = np.array([float(v) for v in parts[1:]], dtype=float)
            embeddings[word] = vec

    dim = next(iter(embeddings.values())).shape[0] if embeddings else 0
    print(f"Loaded {len(embeddings)} Word2Vec embeddings (dim={dim}) from '{filepath}'")
    return embeddings


def binary_entropy(p):
    """Calculates the binary entropy H(p)."""
    if p == 0 or p == 1:
        return 0
    return -p * np.log2(p) - (1 - p) * np.log2(1 - p)


def get_error_probability(n, ne):
    """
    Estimates error probability p(n, ne) such that ne >= (1 - H(p)) * 2^n.
    We assume the equality to find the bound: H(p) = 1 - ne / (2^n).
    """
    target_h = 1 - ne / (2**n)

    # Binary search for p in [0, 0.5]
    low, high = 0.0, 0.5
    for _ in range(50):
        mid = (low + high) / 2
        if binary_entropy(mid) < target_h:
            low = mid
        else:
            high = mid

    p_val = (low + high) / 2
    print(f"p(n={n}, ne={ne}) = {p_val:.4f}")
    return p_val


def estimate_num_layers(n_qubits, n_embedding_qubits, num_data, ath):
    """
    Heuristic formula for estimating L (number of layers).
    L = ceil( #data / (3 * (n + ne) * Ath * p(n, ne)) )
    """
    p = get_error_probability(n_qubits, n_embedding_qubits)

    denominator = 3 * (n_qubits + n_embedding_qubits) * ath
    L = int(np.ceil(num_data / denominator) * p)
    return L


def get_entangling_layer(num_qubits):
    """

    General pattern for n qubits:
      CX(0, n-1)                    <- jump from top to bottom
      CX(n-1, n-2), CX(n-2, n-3), ..., CX(2, 1)   <- staircase up
    """
    qc = QuantumCircuit(num_qubits)
    if num_qubits > 1:
        qc.cx(num_qubits - 1, 0)
        for i in range(num_qubits - 1, 0, -1):
            qc.cx(i - 1, i)

    return qc


def build_parameterized_block(num_qubits, num_layers, param_name):
    """
    Builds one parameterized block of the QWord2Vec circuit (either U or V).

    Both U(θ_u) and V(θ_v) share the same internal structure:
        Per layer: R_X^⊗n → R_Y^⊗n → R_Z^⊗n → U_enta

    Parameters
    ----------
    num_qubits : number of qubits the block acts on (n, the system qubits)
    num_layers : number of layer repetitions (L)
    param_name : name for the ParameterVector (e.g. 'θ_u' or 'θ_v')

    Returns
    -------
    qc    : QuantumCircuit with parameterized gates
    theta : ParameterVector of length 3 * num_qubits * num_layers
    """
    num_params = 3 * num_qubits * num_layers
    theta = ParameterVector(param_name, num_params)

    qc = QuantumCircuit(num_qubits)
    param_idx = 0

    for l in range(num_layers):
        # R_X(θ_x)^⊗n
        for q in range(num_qubits):
            qc.rx(theta[param_idx], q)
            param_idx += 1

        # R_Y(θ_y)^⊗n
        for q in range(num_qubits):
            qc.ry(theta[param_idx], q)
            param_idx += 1

        # R_Z(θ_z)^⊗n
        for q in range(num_qubits):
            qc.rz(theta[param_idx], q)
            param_idx += 1

        enta_layer = get_entangling_layer(num_qubits)
        qc.compose(enta_layer, inplace=True)

        # Visual barrier between layers
        if l < num_layers - 1:
            qc.barrier()

    return qc, theta


def build_full_qword2vec_circuit(n_qubits, n_embedding, num_layers):
    """
    Builds the full QWord2Vec circuit: U(θ_u) → reset → V(θ_v).

    See Fig 1 of QWord2Vec.pdf, it was implemented that schema of circuits.

    Parameters
    ----------
    n_qubits    : total number of system qubits (n)
    n_embedding : number of embedding qubits (n_e), must satisfy n_e < n
    num_layers  : number of layers L (shared by both U and V)

    Returns
    -------
    qc      : full QuantumCircuit (U + reset + V)
    theta_u : ParameterVector for U  (3 * n_qubits * num_layers parameters)
    theta_v : ParameterVector for V  (3 * n_qubits * num_layers parameters)
    """
    u_circuit, theta_u = build_parameterized_block(n_qubits, num_layers, "θ_u")
    v_circuit, theta_v = build_parameterized_block(n_qubits, num_layers, "θ_v")
    qc = QuantumCircuit(n_qubits)

    qc.barrier(label="U(θ_u)")
    qc.compose(u_circuit, inplace=True)

    # Reset no embeddings qubit (n_e..n-1) with value |0⟩
    # Remaining qubits has the output values of U(θ_u).
    # |K> --- U(θ_u) --- embeddings qubit
    qc.barrier(label="reset")
    for q in range(n_embedding, n_qubits):
        qc.reset(q)

    qc.barrier(label="V(θ_v)")
    qc.compose(v_circuit, inplace=True)

    # Output: |ψ⟩
    qc.barrier(label="|ψ⟩")

    return qc, theta_u, theta_v


def encode_input(qc, k, num_qubits):
    """
    Encodes integer k into state |k> (computational basis).
    Uses standard binary mapping.
    """
    fmt = f"{{0:0{num_qubits}b}}"
    binary_k = fmt.format(k)
    for i, bit in enumerate(reversed(binary_k)):
        if bit == "1":
            qc.x(i)


# Para preguntar: Me lía mucho esta parte de generar 32 circuitos para las 32 posibles palabras.
def prepare_transpiled_circuits(qc, n_qubits, sim):
    """
    Pre-compiles the circuits for all possible input words.
    """
    circuits = []
    num_words = 2**n_qubits
    for k in range(num_words):
        temp_qc = QuantumCircuit(n_qubits)
        encode_input(temp_qc, k, n_qubits)
        temp_qc.compose(qc, inplace=True)
        temp_qc.save_statevector()
        circuits.append(temp_qc)
    return transpile(circuits, sim)


def get_embeddings_batched(params, theta_params, t_circuits, sim, num_qubits):
    """
    Efficiently computes Bloch vectors using pre-transpiled circuits and parameter binding.
    """
    num_words = len(t_circuits)

    # Bind parameters efficiently to the transpiled circuits
    # Since we want to apply the SAME global parameters to all circuits:
    # Converted to python floats to avoid AerSimulator errors
    clean_params = [float(p) for p in params]
    bind_dict = dict(zip(theta_params, clean_params))

    # Create bound circuits (assign_parameters returns new copies by default)
    bound_circuits = [c.assign_parameters(bind_dict) for c in t_circuits]

    job = sim.run(bound_circuits, shots=1)
    result = job.result()

    embeddings = []
    traced_qubits = list(range(1, num_qubits))

    pauli_x = Pauli("X")
    pauli_y = Pauli("Y")
    pauli_z = Pauli("Z")

    for i in range(num_words):
        state = result.get_statevector(i)
        rho_0 = partial_trace(state, traced_qubits)
        x = rho_0.expectation_value(pauli_x).real
        y = rho_0.expectation_value(pauli_y).real
        z = rho_0.expectation_value(pauli_z).real

        embeddings.append([x, y, z])

    return np.array(embeddings)


def calculate_cross_entropy(embeddings, num_words, training_data):
    """
    Calculates the Cross Entropy Loss (Skip-Gram style approximation)
    using the provided synthetic training data.

    training_data: dict { target_word_idx: [context_idx1, context_idx2] }

    Formula: -log(sigmoid(u . v)) for positive pairs
    """
    loss = 0.0

    # Create List of Positive Pairs from Training Data
    positive_pairs = []
    for target_word, context_words in training_data.items():
        for context_word in context_words:
            positive_pairs.append((target_word, context_word))

    def sigmoid(x):
        return 1 / (1 + np.exp(-x))

    # Compute Loss for Positive Pairs
    for i, j in positive_pairs:
        u = embeddings[i]
        v = embeddings[j]

        # Dot product of embeddings (measures similarity in Hilbert space)
        score = np.dot(u, v)
        loss += -np.log(sigmoid(score))

    if len(positive_pairs) == 0:
        return 0.0

    return loss / len(positive_pairs)


def calculate_custom_loss(
    params, theta_params, t_circuits, sim, n_qubits, target_distances, training_data, C
):
    """
    Implements the custom loss function from the paper:
    Loss = CrossEntropy - C * CorrelationCoefficient(EmbeddingData, TrainingLabels)
    It's implemented in that way to retain the relationships that may not be preserved
    after the measurement. It forces the circuit to "maintain" the relationships and distances.
    """
    q_embeddings = get_embeddings_batched(
        params, theta_params, t_circuits, sim, n_qubits
    )

    # Calculate Distance Vector for Quantum Embeddings (Euclidean)
    q_dists = pdist(q_embeddings, metric="euclidean")

    # Calculate Correlation with Target Distances
    if len(target_distances) != len(q_dists):
        correlation = 0.0
    else:
        correlation, _ = pearsonr(q_dists, target_distances)

    # Calculates the semantic loss based on the current embeddings
    num_words = 2**n_qubits
    cross_entropy = calculate_cross_entropy(q_embeddings, num_words, training_data)

    # Total Loss
    return cross_entropy - (C * correlation)


def train_qword2vec(
    qc,
    theta_params,
    initial_params,
    n_qubits,
    training_data,
    epochs=100,
    c_val=1.0,
    learning_rate=0.001,
    momentum=0.9,
    perturbation=0.1,
):
    """
    Trains Q-Word2Vec using SPSA gradient estimation + SGD with momentum.

    Following the paper (Ohno et al.): stochastic gradient descent with
    lr=0.001 and momentum term=0.9, using SPSA (Gacon et al. 2021) to
    approximate the gradient with only two loss evaluations per step.

    Returns
    -------
    params       : np.ndarray  – optimized parameters
    loss_history : list[float] – loss approximation per epoch
    """
    # Initialize Simulator and Pre-Transpile Circuits ONCE
    sim = AerSimulator()
    t_circuits = prepare_transpiled_circuits(qc, n_qubits, sim)

    # Prepare Target Distances
    num_pairs = (2**n_qubits * (2**n_qubits - 1)) // 2
    dummy_targets = np.random.rand(num_pairs)

    def loss_function(p):
        return calculate_custom_loss(
            p,
            theta_params,
            t_circuits,
            sim,
            n_qubits,
            dummy_targets,
            training_data,
            c_val,
        )

    # --- SGD + SPSA initialisation ---
    params = np.array(initial_params, dtype=float)
    velocity = np.zeros_like(params)  # momentum accumulator
    loss_history = []

    print(
        f"\nStarting SGD + SPSA Optimisation  "
        f"(lr={learning_rate}, momentum={momentum}, perturbation={perturbation})"
    )

    for epoch in range(epochs):
        # Step 1 – Random Bernoulli perturbation vector δ_k ∈ {-1, +1}^d
        delta = np.random.choice([-1.0, 1.0], size=len(params))

        # Step 2 – Evaluate loss at θ ± c·δ and approximate gradient
        loss_plus = loss_function(params + perturbation * delta)
        loss_minus = loss_function(params - perturbation * delta)
        grad = (loss_plus - loss_minus) / (2.0 * perturbation * delta)

        # Step 3 & 4 – SGD with momentum update
        velocity = momentum * velocity + learning_rate * grad
        params = params - velocity

        # Track loss as the mean of the two SPSA evaluations
        current_loss = (loss_plus + loss_minus) / 2.0
        loss_history.append(current_loss)

        if (epoch + 1) % 10 == 0 or epoch == 0:
            print(f"  Epoch {epoch + 1:>4}/{epochs}  |  Loss ≈ {current_loss:.6f}")

    print(f"\nOptimisation Complete. Final Loss ≈ {loss_history[-1]:.4f}")

    # Final error rate
    final_embeddings = get_embeddings_batched(
        params, theta_params, t_circuits, sim, n_qubits
    )
    final_error_rate = calculate_error_rate(final_embeddings, training_data)
    print(f"Final Error Rate on Training Data: {final_error_rate:.4f}")

    return params, loss_history


def load_corpus(file_path):
    """
    Reads the corpus from a text file.
    Returns a list of sentences (lists of words).
    """
    with open(file_path, "r") as f:
        lines = f.readlines()

    # Simple tokenization: lowercase and split
    corpus = [line.strip().lower().split() for line in lines]
    return corpus


def build_vocabulary(corpus, n_qubits):
    """
    Builds a vocabulary from the corpus.
    Maps words to integers 0 to 2^n - 1.
    """
    unique_words = set()
    for sentence in corpus:
        unique_words.update(sentence)

    sorted_words = sorted(list(unique_words))
    vocab_size = len(sorted_words)
    max_vocab = 2**n_qubits

    if vocab_size > max_vocab:
        print(f"Warning: Corpus has {vocab_size} words, truncating to {max_vocab}.")
        sorted_words = sorted_words[:max_vocab]

    word_to_id = {w: i for i, w in enumerate(sorted_words)}
    id_to_word = {i: w for i, w in enumerate(sorted_words)}

    return word_to_id, id_to_word


def generate_training_data_from_text(corpus, word_to_id, window_size=1):
    """
    Generates training data pairs using Skip-Gram approach.
    Returns: { target_id: [context_id1, context_id2, ...] }
    """
    training_data = {}

    # Initialize entries for all vocab words
    for idx in word_to_id.values():
        training_data[idx] = []

    for sentence in corpus:
        indices = [word_to_id[w] for w in sentence if w in word_to_id]

        for i, target_idx in enumerate(indices):
            # Window range
            start = max(0, i - window_size)
            end = min(len(indices), i + window_size + 1)

            for j in range(start, end):
                if i != j:
                    context_idx = indices[j]
                    training_data[target_idx].append(context_idx)

    # Remove duplicates
    final_data = {}
    for t, contexts in training_data.items():
        if contexts:
            final_data[t] = contexts

    return final_data


def calculate_error_rate(embeddings, training_data):
    """
    Calculates the 'error rate' metric:
    Sum of mismatches between the two surrounding words of the model output
    and the training data labels, divided by (2 * total number of training samples).

    Model output for word w is the vector of dot products [w . v_0, w . v_1, ... w . v_N].
    """
    mismatches = 0
    num_samples = len(training_data)

    for word_idx, targets in training_data.items():
        u = embeddings[word_idx]

        # Scores with all other embeddings
        scores = np.dot(embeddings, u)
        scores[word_idx] = -np.inf

        # Find the indices of the top 2 scores
        top_2_indices = np.argsort(scores)[-2:]

        # Mismatch if a predicted top-2 index is NOT in the target list
        current_mismatches = 0
        for pred_idx in top_2_indices:
            if pred_idx not in targets:
                current_mismatches += 1

        mismatches += current_mismatches

    return mismatches / (2 * num_samples)


if __name__ == "__main__":
    # System size
    n_qubits = 4
    # Embedding size
    n_embedding = 2

    print(f"--- Q-Word2Vec Full Model (n={n_qubits}, ne={n_embedding}) ---")

    try:
        corpus = load_corpus("smallCorpora.txt")
        print("Corpus loaded successfully.")
    except FileNotFoundError:
        print("Error: smallCorpora.txt not found. Please create it.")
        exit(1)

    # --- Load Word2Vec reference embeddings ---
    # These are generated by word2Vec.py and used to assess embedding quality.
    # Run word2Vec.py once; afterwards the files are cached and reused.
    try:
        w2v_embeddings = load_word2vec_embeddings("word2vec_embeddings.txt")
        w2v_embeddings_2d = load_word2vec_embeddings("word2vec_embeddings_2d.txt")
    except FileNotFoundError as e:
        print(f"\n[WARNING] {e}")
        print("[WARNING] Continuing without Word2Vec reference embeddings.\n")
        w2v_embeddings = {}
        w2v_embeddings_2d = {}

    word_to_id, id_to_word = build_vocabulary(corpus, n_qubits)
    print(f"Vocabulary Size: {len(word_to_id)}/{2**n_qubits}")

    # Generate Training Data from Text
    training_data = generate_training_data_from_text(corpus, word_to_id, window_size=1)

    # Heuristic Estimation of L using actual number pairs of training data
    num_data = len(corpus)
    ath = 0.02

    n_layers = estimate_num_layers(n_qubits, n_embedding, num_data, ath)
    print(f"Heuristic L = {n_layers} (using #pairs={num_data}, Ath={ath})")

    # Construcción del circuito completo: U(θ_u) → reset → V(θ_v)
    qc, theta_u, theta_v = build_full_qword2vec_circuit(n_qubits, n_embedding, n_layers)
    # El optimizador trabaja con todos los parámetros concatenados
    all_theta = list(theta_u) + list(theta_v)
    theta_vals = np.random.uniform(0, 2 * np.pi, len(all_theta))

    # --- Dibujo del circuito completo para verificación ---
    print("\n--- Circuit Diagram (U + reset + V) ---")
    qc_draw, _, _ = build_full_qword2vec_circuit(
        n_qubits, n_embedding, min(n_layers, 2)
    )
    cols_per_row = max(1, qc_draw.depth() // 2 + 1)
    fig = qc_draw.draw(output="mpl", fold=cols_per_row)
    fig.suptitle(
        f"QWord2Vec Full Circuit  [U(θ_u) → reset → V(θ_v)]\n"
        f"n={n_qubits} qubits,  ne={n_embedding} embedding,  L={min(n_layers, 2)} layers",
        fontsize=15,
        fontweight="bold",
        y=1.0,
    )
    local_path = "qword2vec_circuit.png"
    fig.savefig(local_path, dpi=150, bbox_inches="tight")
    print(f"Circuit diagram saved to: {local_path}")

    try:
        memoria_dir = os.path.join(
            os.path.dirname(os.path.abspath(__file__)), "..", "memoria", "imagenes"
        )
        os.makedirs(memoria_dir, exist_ok=True)
        memoria_path = os.path.join(memoria_dir, "qword2vec_circuit.png")
        fig.savefig(memoria_path, dpi=150, bbox_inches="tight")
        print(f"Circuit diagram saved to: {memoria_path}")
    except Exception:
        print(
            "[Aviso] No se ha guardado la imagen en memoria/imagenes: "
            "esta ruta solo existe dentro del proyecto del TFG."
        )
    plt.show()

    # Demo de optimización SPSA con todos los parámetros (θ_u + θ_v)
    theta_vals, loss_history = train_qword2vec(
        qc,
        all_theta,
        theta_vals,
        n_qubits,
        training_data,
        epochs=100,
        c_val=0,
        learning_rate=0.001,
        momentum=0.9,
        perturbation=0.1,
    )

    print(f"Computing Bloch vectors for all {2**n_qubits} input words...")

    # Efficient Batch Calculation for Visualization
    num_words = 2**n_qubits
    sim = AerSimulator()
    t_circuits = prepare_transpiled_circuits(qc, n_qubits, sim)
    embeddings = get_embeddings_batched(
        theta_vals, all_theta, t_circuits, sim, n_qubits
    )

    # Unpack for plotting
    xs = embeddings[:, 0]
    ys = embeddings[:, 1]
    zs = embeddings[:, 2]

    print(f"Vectors computed: {len(xs)}")
    print("Plotting scattered points on Bloch Sphere...")

    # Visualization
    try:
        b = Bloch()

        # Generate distinct colors for 32 points using a colormap
        cmap = plt.get_cmap("hsv")  # 'hsv' gives a nice rainbow cycle
        colors = [cmap(i / num_words) for i in range(num_words)]

        # Clear default point colors/markers to set our own
        b.point_color = []
        b.point_marker = []

        for i in range(num_words):
            # Add point i as a list of lists [[x], [y], [z]]
            b.add_points([[xs[i]], [ys[i]], [zs[i]]])
            # Set style for this point
            b.point_color.append(colors[i])
            b.point_marker.append("o")

        # Qiskit/Matplotlib Fix: Use render() and plt.show()
        if hasattr(b, "render"):
            b.render()

        plt.show()

    except NameError:
        print(
            "Error: Bloch class not available. Please install qutip or check qiskit visualization."
        )
    except TypeError as e:
        print(f"Visualization warning: {e}")
        plt.show()
